// Positions are local to this entry; layout.ts explains the coordinates.
import type { Segment } from "../types"

export const A: Segment = {
  id: "A",
  name: "A block",
  kind: "block",
  letter: "A",
  from: -55,
  to: -41,
  facade: "glass",
  pane: [1, 1.3],
  tint: "#3f5866",
  letterAt: [1.8, 3.45, 0.9],
  notes:
    "Accounts office behind the glass at Level 1. The library is upstairs, up the stairs to the VIT box.",
  pieces: [
    {
      name: "VIT glass box",
      kind: "box",
      at: [1.5, 6.25, 11],
      size: [3, 4.5, 8.5],
      mat: "darkGlass",
    },
    {
      name: "VIT box soffit",
      kind: "box",
      at: [1.5, 3.99, 11],
      size: [3, 0.04, 8.5],
      mat: "panel",
    },
    {
      kind: "railPath",
      points: [
        [0.1, 6.8],
        [2.95, 6.8],
        [2.95, 15.2],
        [0.1, 15.2],
      ],
      y: 8.5,
    },
    {
      kind: "sign",
      text: "VIT",
      at: [3.02, 6.5, 8.7],
      height: 1.3,
      bg: "#1f2a31",
    },
    {
      kind: "sign",
      text: "Vidyalankar Institute of Technology",
      at: [3.02, 6.8, 12.6],
      height: 0.36,
      bg: "#1f2a31",
    },
    {
      kind: "sign",
      text: "www.vit.edu.in",
      at: [3.02, 6.25, 12.6],
      height: 0.22,
      bg: "#1f2a31",
    },
    {
      name: "Stair, first flight",
      kind: "stairs",
      out: 1.8,
      along: [8, 1.6],
      y: [0, 4],
      width: 1.4,
      look: "steel",
    },
    {
      name: "Stair landing",
      kind: "box",
      at: [1.8, 3.9, 0.9],
      size: [1.6, 0.2, 1.4],
      mat: "chequer",
    },
    {
      name: "Stair, second flight",
      kind: "stairs",
      out: 1.8,
      along: [1.6, 7.6],
      y: [4, 8.3],
      width: 1.4,
      look: "steel",
    },
    {
      name: "Accounts counter",
      kind: "box",
      at: [0.5, 0.53, 11],
      size: [0.45, 1.05, 5],
      mat: "white",
    },
    { kind: "stools", from: [1.1, 8.9], to: [1.1, 13.2], count: 8 },
    {
      name: "Pavers along the accounts glass",
      kind: "decal",
      at: [1.25, 7],
      size: [2.5, 14],
      mat: "paver",
    },
    {
      kind: "standee",
      at: [4.4, 5.6],
      color: "#1e5fa8",
      text: "V-CITE",
    },
    {
      kind: "standee",
      at: [4.4, 6.7],
      color: "#24324f",
      text: "STARTUP\nARENA",
    },
    { kind: "standee", at: [0.7, 13.6], color: "#111111" },
    { kind: "flag", at: [7.5, 9], color: "#5b3a8c" },
    { kind: "flag", at: [8, 9.6], color: "#b3262e" },
    { kind: "flag", at: [8.5, 10.2], color: "#2f8f4e" },
    { kind: "flag", at: [9, 10.8], color: "#7a1f2b" },
    { kind: "label", text: "Library (upstairs)", at: [2, 11.5, 4] },
  ],
}
