// Positions are local to this entry; layout.ts explains the coordinates.
import type { Piece, Segment } from "../types"

const fin = (a: number, out: number): Piece => ({
  kind: "box",
  at: [out, 2.1, a],
  size: [0.5, 3, 0.25],
  mat: "slate",
})

export const B: Segment = {
  id: "B",
  name: "B block",
  kind: "block",
  letter: "B",
  from: -21,
  to: -7,
  upper: "light",
  ground: "plain",
  recess: [0, 2.5, 4],
  tint: "#3b5aa3",
  letterAt: [1.05, 2.8, 6.5],
  notes:
    "A curved white base with the B sign and a steel stair up to a chequer-plate landing over the reception. Above: the blue wall at Level 2 and the big OSB-clad box near the roof.",
  pieces: [
    {
      name: "Curved base",
      kind: "bulge",
      along: [2.5, 11],
      out: 0,
      depth: 1,
      y: [0, 4],
      mat: "white",
      back: 0.3,
      solid: true,
    },
    fin(2.9, 0.4),
    fin(3.35, 0.5),
    fin(3.8, 0.62),
    {
      kind: "board",
      at: [1.04, 1.5, 6],
      width: 0.5,
      height: 0.7,
      bg: "#1d7f86",
      text: "FOLLOW\nYOUR\nINSTINCTS",
    },
    {
      kind: "board",
      at: [1.04, 1.5, 7.2],
      width: 0.5,
      height: 0.7,
      bg: "#22252b",
      text: "LOOK\nWITHIN",
    },
    {
      kind: "board",
      at: [-1.5, 1.6, 2.47],
      width: 0.4,
      height: 1.5,
      bg: "#1f4fa0",
      text: "BLOCK\nB",
      face: "west",
    },
    {
      kind: "box",
      at: [-3.97, 1.1, 1.25],
      size: [0.06, 2.2, 1.1],
      mat: "wood",
    },
    {
      name: "B stair",
      kind: "stairs",
      out: 1.9,
      along: [3, 10],
      y: [0, 2.75],
      width: 1.3,
      look: "steel",
    },
    {
      name: "Landing",
      kind: "box",
      at: [2.1, 2.65, 12.1],
      size: [4.2, 0.2, 4.2],
      mat: "chequer",
    },
    { kind: "box", at: [4.15, 2.4, 12.1], size: [0.1, 0.45, 4.2], mat: "navy" },
    { kind: "box", at: [2.1, 2.4, 14.15], size: [4.2, 0.45, 0.1], mat: "navy" },
    {
      kind: "railPath",
      points: [
        [4.15, 10.1],
        [4.15, 14.15],
        [0.1, 14.15],
      ],
      y: 2.75,
    },
    { kind: "column", at: [4, 14.2], y: [0, 2.55], r: 0.15, mat: "steel" },
    {
      kind: "flight",
      from: [2.6, 13.35],
      to: [0.3, 13.35],
      y: [2.75, 4],
      width: 1.3,
      look: "steel",
    },
    {
      name: "Reception desk",
      kind: "box",
      at: [2, 0.53, 12.3],
      size: [0.7, 1.05, 2.5],
      mat: "tan",
      solid: true,
    },
    {
      kind: "board",
      at: [0.03, 1.6, 12.3],
      width: 2.4,
      height: 1.2,
      bg: "#c8a46e",
    },
    { kind: "box", at: [0.04, 1.1, 10.6], size: [0.06, 2.2, 1.1], mat: "wood" },
    {
      name: "Level 2 balcony",
      kind: "curvedBalcony",
      along: [1.5, 10],
      out: 0,
      depth: 1.5,
      y: 4,
    },
    {
      name: "Blue wall",
      kind: "box",
      at: [-2.15, 5.8, 7.55],
      size: [0.1, 3.6, 9.5],
      mat: "blue",
    },
    {
      kind: "glazing",
      at: [-2.08, 4.4, 7.55],
      width: 9,
      height: 0.5,
      cols: 8,
      rows: 1,
    },
    {
      kind: "board",
      at: [-2.08, 6, 7.55],
      width: 1.8,
      height: 1,
      bg: "#5d7d4a",
    },
    {
      kind: "box",
      at: [-2.05, 7.2, 7.55],
      size: [0.06, 0.05, 1.2],
      mat: "light",
    },
    { kind: "column", at: [-0.5, 3], y: [4, 8], r: 0.2, mat: "white" },
    { kind: "column", at: [-0.5, 11.5], y: [4, 8], r: 0.2, mat: "white" },
    {
      name: "OSB box",
      kind: "bulge",
      along: [0.2, 14.4],
      out: -1.5,
      depth: 2.3,
      y: [8, 14.7],
      mat: "osb",
      back: 2,
    },
    {
      kind: "bulge",
      along: [0.2, 14.4],
      out: -1.5,
      depth: 2.3,
      y: [7.8, 8],
      mat: "white",
      back: 2,
    },
    {
      name: "OSB box window",
      kind: "glazing",
      at: [0.03, 12.3, 11.4],
      width: 4.5,
      height: 3,
      cols: 4,
      rows: 2,
      turn: 21,
    },
  ],
}
