// Positions are local to this entry; layout.ts explains the coordinates.
import type { Piece, Segment } from "../types"
import { CANTEEN } from "./c-canteen"

// The canteen box starts 9 m along, after the plain front; its front is 9 bays of 1.13 m.
const A0 = 9
// The plain front west of the canteen sits 2.6 m back.
const BACK = -2.57
const pendants: Piece = {
  kind: "pendants",
  from: [1.3, A0 + 1.8],
  to: [1.3, A0 + 9.8],
  count: 6,
  y: 2.75,
  top: 3.7,
}

export const C: Segment = {
  id: "C",
  name: "C block",
  kind: "block",
  letter: "C",
  from: -3,
  to: 20.4,
  tint: "#e3dccb",
  upper: "light",
  ground: "plain",
  recess: [0, A0, 2.6],
  hollow: [5, 21],
  letterAt: [2.52, 5.2, A0 + 5.3],
  notes:
    "Cafeteria C-101 is the polycarbonate box at Level 1. Ribbons & Balloons and the washrooms are at the west end behind the plain front; the booths and the orange wall are at the east end.",
  pieces: [
    {
      kind: "board",
      at: [BACK, 1.6, 0.8],
      width: 0.55,
      height: 1.1,
      bg: "#1d4fae",
      text: "C BLOCK\nDIRECTORY",
    },
    {
      name: "NutriTap",
      kind: "vending",
      at: [-2.1, 1.9],
      color: "#1f2f5c",
      text: "NutriTap",
    },
    {
      name: "Bin",
      kind: "box",
      at: [-2.3, 0.45, 2.7],
      size: [0.45, 0.9, 0.45],
      mat: "leaf",
    },
    {
      name: "Bin",
      kind: "box",
      at: [-2.3, 0.45, 3.2],
      size: [0.45, 0.9, 0.45],
      mat: "blue",
    },
    {
      kind: "board",
      at: [BACK, 2.9, 4.7],
      width: 2,
      height: 1.4,
      bg: "#b3282d",
      text: "SUCCESS",
    },
    {
      kind: "board",
      at: [BACK, 2, 6.1],
      width: 0.5,
      height: 1.3,
      bg: "#e8742a",
      text: "SEIZE\nTHE\nMOMENT",
    },
    {
      kind: "board",
      at: [BACK - 0.01, 1.8, 7.4],
      width: 0.95,
      height: 1.25,
      bg: "#9b2226",
    },
    {
      kind: "glazing",
      at: [BACK + 0.01, 1.8, 7.4],
      width: 1,
      height: 1.3,
      cols: 2,
      rows: 2,
    },
    { kind: "stand", at: [-1.4, 8.3], bg: "#1b1b1b" },
    {
      kind: "board",
      at: [-2.15, 5.7, 3.5],
      width: 2.4,
      height: 0.7,
      bg: "#24407a",
      text: "Vidyalankar Live on a 'click'",
    },
    {
      name: "Navy pillar",
      kind: "box",
      at: [0.25, 8, 0.35],
      size: [0.5, 8, 0.7],
      mat: "navy",
    },
    {
      kind: "box",
      at: [0.25, 11.75, 1.4],
      size: [0.5, 0.5, 2.8],
      mat: "navy",
    },
    {
      name: "Canteen west side",
      kind: "box",
      at: [1, 1.95, A0],
      size: [2, 3.9, 0.08],
      mat: "polycarb",
    },
    {
      name: "Canteen corner",
      kind: "shape",
      points: [
        [1.98, A0 - 0.03],
        [2.52, A0 + 0.45],
        [2.46, A0 + 0.5],
        [1.92, A0 + 0.02],
      ],
      y: [0, 3.9],
      mat: "polycarb",
    },
    {
      name: "Canteen east side",
      kind: "box",
      at: [1.25, 1.95, A0 + 10.65],
      size: [2.5, 3.9, 0.08],
      mat: "polycarb",
    },
    {
      name: "Canteen front",
      kind: "bays",
      out: 2.5,
      along: [A0 + 0.45, A0 + 10.65],
      height: 3.9,
      count: 9,
      clear: [4, 6, 8],
      door: 2,
    },
    {
      name: "Canteen roof",
      kind: "box",
      at: [1.3, 3.98, A0 + 5.3],
      size: [2.7, 0.16, 10.8],
      mat: "white",
    },
    {
      name: "Canteen ceiling",
      kind: "box",
      at: [1.25, 3.72, A0 + 5.3],
      size: [2.4, 0.05, 10.5],
      mat: "soffit",
    },
    { kind: "awning", out: 2.5, along: [A0, A0 + 10.65], y: 2.9, depth: 0.9 },
    {
      kind: "board",
      at: [2.54, 1.67, A0 + 1.35],
      width: 0.35,
      height: 0.55,
      bg: "#1d4fae",
      text: "Cafeteria\nC-101",
    },
    pendants,
    ...CANTEEN,
    {
      name: "Frame column",
      kind: "box",
      at: [2.2, 8.65, A0 + 1.7],
      size: [0.6, 9.5, 0.6],
      mat: "beam",
    },
    {
      name: "Frame column",
      kind: "box",
      at: [2.2, 8.65, A0 + 5.3],
      size: [0.6, 9.5, 0.6],
      mat: "beam",
    },
    {
      name: "Frame top beam",
      kind: "box",
      at: [2.2, 13.2, A0 + 6.95],
      size: [0.7, 0.8, 11.1],
      mat: "beam",
    },
    {
      name: "Frame side beam",
      kind: "box",
      at: [1.1, 13.2, A0 + 1.4],
      size: [2.2, 0.8, 0.5],
      mat: "beam",
    },
    {
      name: "Frame side beam",
      kind: "box",
      at: [1.1, 13.2, A0 + 12.5],
      size: [2.2, 0.8, 0.5],
      mat: "beam",
    },
    {
      name: "Frame Level 3 beam",
      kind: "box",
      at: [2.2, 8, A0 + 7.25],
      size: [0.5, 0.6, 11.1],
      mat: "beam",
    },
    {
      name: "Frame brace",
      kind: "strut",
      from: [2.2, 12.9, A0 + 1.7],
      to: [2.2, 8.2, A0 + 4.2],
      size: [0.35, 0.35],
    },
    {
      kind: "board",
      at: [2.52, 5.5, A0 + 1.7],
      width: 0.25,
      height: 0.6,
      bg: "#c0392b",
    },
    // Cafe tables outside, leaving the way to the door in bay 2 clear.
    { kind: "table", at: [3.4, A0 + 0.3] },
    { kind: "table", at: [3.4, A0 + 4.4] },
    { kind: "table", at: [3.4, A0 + 6.8] },
    { kind: "table", at: [3.4, A0 + 9.2] },
    {
      name: "Raised landing",
      kind: "box",
      at: [1.5, 0.65, A0 + 12.8],
      size: [3, 1.3, 5],
      mat: "panel",
      solid: true,
    },
    {
      kind: "railPath",
      points: [
        [3, A0 + 10.4],
        [3, A0 + 15.2],
      ],
      y: 1.3,
    },
    {
      name: "Steps up from the Nescafe side",
      kind: "stairs",
      out: 1.5,
      along: [A0 + 17.8, A0 + 15.3],
      y: [0, 1.3],
      width: 1.6,
      look: "steel",
    },
    {
      name: "Blue bridge to D",
      kind: "bridge",
      from: [1, A0 + 12],
      to: [1, A0 + 23.5],
      y: 4,
      width: 2,
    },
    { kind: "label", text: "Canteen", at: [1.5, 6.5, A0 + 5.3] },
  ],
}
