// Positions are local to this entry; layout.ts explains the coordinates.
import type { Segment } from "../types"

export const EXAM: Segment = {
  id: "exam",
  name: "Exam department",
  kind: "block",
  from: -37.5,
  to: -21,
  tint: "#d9d4c7",
  upper: "light",
  notes:
    "A convex white front with the phone box, print kiosk and ATM, a curved balcony and a leaning sail wall above, and the stone prow toward B.",
  pieces: [
    {
      name: "Exam department front",
      kind: "bulge",
      along: [0, 6.5],
      out: 0,
      depth: 5,
      y: [0, 4],
      mat: "plaster",
      back: 0.5,
      solid: true,
      windows: { y: [1.5, 2.6], count: 7 },
    },
    {
      name: "Banner",
      kind: "board",
      at: [5.06, 3.45, 3.25],
      width: 3,
      height: 1.2,
      bg: "#1f2f5c",
      text: "You are on the campus\nthat grooms Global citizens",
    },
    {
      name: "Level 2 balcony",
      kind: "curvedBalcony",
      along: [0, 6.5],
      out: 0,
      depth: 4.6,
      y: 4,
    },
    {
      name: "Sail wall",
      kind: "bulge",
      along: [-1.5, 6.5],
      out: 0,
      depth: 3.2,
      y: [4, 8.5],
      mat: "plaster",
      back: 0.5,
      windows: { y: [5.6, 6.4], count: 4, mat: "darkGlass" },
    },
    {
      name: "Strip-window box",
      kind: "box",
      at: [2.4, 6.4, 0.2],
      size: [1.4, 1.6, 2.2],
      mat: "white",
    },
    {
      kind: "glazing",
      at: [3.12, 6.4, 0.2],
      width: 1.8,
      height: 0.7,
      mat: "darkGlass",
      cols: 3,
      rows: 1,
    },
    {
      name: "Steel stair to Level 3",
      kind: "stairs",
      out: -1.2,
      along: [7, 12.5],
      y: [4, 8],
      width: 1.2,
      look: "steel",
    },
    {
      name: "Blue wall",
      kind: "box",
      at: [-2.15, 9.5, 9],
      size: [0.1, 3, 4.5],
      mat: "blue",
    },
    { kind: "phonebox", at: [5.5, 3.6] },
    {
      name: "Print kiosk",
      kind: "vending",
      at: [4.6, 4.6],
      color: "#1e63b5",
      text: "Skip the Queue.\nPrint in Seconds.",
    },
    {
      name: "ATM",
      kind: "vending",
      at: [3.1, 5.5],
      color: "#232a30",
      text: "ATM",
    },
    {
      name: "Stone prow",
      kind: "shape",
      points: [
        [4, 6.5],
        [8, 7.5],
        [5.5, 10],
        [3, 13],
        [1, 16.5],
        [0, 16.5],
        [0, 6.5],
      ],
      y: [0, 6.3],
      mat: "stone",
      solid: true,
    },
    {
      name: "Fin",
      kind: "box",
      at: [6.6, 5.3, 8],
      size: [1.6, 0.12, 0.5],
      mat: "slate",
    },
    {
      name: "Fin",
      kind: "box",
      at: [6.6, 5.7, 8],
      size: [1.6, 0.12, 0.5],
      mat: "slate",
    },
    {
      name: "Fin",
      kind: "box",
      at: [6.6, 6.1, 8],
      size: [1.6, 0.12, 0.5],
      mat: "slate",
    },
    {
      name: "Glass door in the prow",
      kind: "glazing",
      at: [2.1, 1.45, 14.6],
      width: 3,
      height: 2.9,
      cols: 3,
      rows: 3,
      turn: 30,
    },
    {
      name: "Navy strip",
      kind: "box",
      at: [0.35, 3, 6.5],
      size: [0.7, 6, 0.3],
      mat: "navy",
    },
    { kind: "label", text: "Exam dept", at: [3, 9, 3] },
  ],
}
