// Positions are local to this entry; layout.ts explains the coordinates.
import type { Piece, Segment, Vec2 } from "../types"

const orange: Vec2[] = [
  [0, 6],
  [4.6, 6],
  [4.2, 16],
  [0, 16],
]

const rib = (a: number): Piece => ({
  kind: "strut",
  from: [0.3, 6.72, a],
  to: [4.1, 6.72, a + 3],
  size: [0.12, 0.22],
  mat: "black",
})

const slot = (y: number): Piece => ({
  kind: "glazing",
  at: [4.54, y, 8.4],
  width: 2.2,
  height: 0.3,
  mat: "darkGlass",
  cols: 1,
  rows: 1,
  turn: -2.3,
})

export const F_EAST: Segment = {
  id: "F-east",
  name: "F block east",
  kind: "block",
  from: -4,
  to: 20,
  depth: 9.5,
  upper: "light",
  ground: "plain",
  recess: [0, 9, 2.5],
  tint: "#c4622c",
  notes:
    "F's recess and stair, then the tan base under a black band and the cantilevered orange box, and a white volume over the General Notices wall by Gate 2.",
  pieces: [
    { kind: "box", at: [-2.47, 1.1, 2.4], size: [0.06, 2.2, 1.1], mat: "wood" },
    { kind: "box", at: [-2.47, 1.1, 7.2], size: [0.06, 2.2, 1.1], mat: "wood" },
    {
      kind: "board",
      at: [-2.46, 2.65, 2.4],
      width: 0.9,
      height: 0.3,
      bg: "#1f2f6b",
      text: "Department",
    },
    {
      kind: "board",
      at: [-2.46, 1.6, 4.8],
      width: 1.4,
      height: 1,
      bg: "#f1efe8",
      text: "General Notices",
      fg: "#2a2a2a",
    },
    { kind: "lights", from: [-1.2, 0.5], to: [-1.2, 8.5], y: 3.7 },
    {
      name: "F stair",
      kind: "flight",
      from: [1.5, -3],
      to: [1.5, 3],
      y: [0, 2.8],
      width: 1.7,
      look: "steel",
    },
    {
      name: "Stair landing",
      kind: "box",
      at: [1.5, 2.7, 4],
      size: [1.9, 0.2, 2],
      mat: "chequer",
    },
    {
      kind: "railPath",
      points: [
        [2.45, 3.05],
        [2.45, 5],
      ],
      y: 2.8,
    },
    { kind: "column", at: [1.5, 4.6], y: [0, 2.6], r: 0.1, mat: "steel" },
    {
      kind: "flight",
      from: [1.5, 5],
      to: [1.5, 7.4],
      y: [2.8, 4],
      width: 1.5,
      look: "concrete",
    },
    {
      kind: "box",
      at: [1, 3.9, 8],
      size: [2, 0.2, 1.2],
      mat: "white",
    },
    {
      name: "Tan base",
      kind: "shape",
      points: [
        [0, 8.5],
        [3, 8.5],
        [3.5, 10],
        [3.7, 11.5],
        [3.6, 13],
        [3.1, 14.4],
        [2, 15.3],
        [0, 15.6],
      ],
      y: [0, 4.7],
      mat: "tan",
      solid: true,
    },
    {
      name: "Frosted doors",
      kind: "glazing",
      at: [3.64, 1.4, 10.8],
      width: 2.4,
      height: 2.8,
      mat: "frosted",
      cols: 4,
      rows: 2,
      turn: 7,
    },
    {
      kind: "glazing",
      at: [3.31, 3.9, 13.9],
      width: 0.8,
      height: 0.25,
      mat: "darkGlass",
      cols: 1,
      rows: 1,
      turn: -20,
    },
    {
      name: "Black band",
      kind: "shape",
      points: [
        [0, 8.5],
        [2.9, 8.5],
        [3.1, 11.5],
        [2.9, 14.5],
        [0, 15.2],
      ],
      y: [4.7, 7],
      mat: "black",
    },
    {
      kind: "glazing",
      at: [3.13, 5.75, 11.5],
      width: 2.4,
      height: 0.7,
      cols: 4,
      rows: 1,
    },
    {
      name: "Orange box",
      kind: "shape",
      points: orange,
      y: [7, 12.2],
      mat: "orange",
    },
    { kind: "shape", points: orange, y: [6.85, 7], mat: "black" },
    rib(6.4),
    rib(9.4),
    rib(12.4),
    slot(9.7),
    slot(10.3),
    slot(10.9),
    {
      name: "White volume by Gate 2",
      kind: "box",
      at: [2.5, 6.9, 20],
      size: [5, 5.8, 8],
      mat: "white",
    },
    {
      kind: "box",
      at: [1.25, 2, 20],
      size: [2.5, 4, 8],
      mat: "plaster",
      solid: true,
    },
    { kind: "column", at: [4.6, 23.6], y: [0, 4], r: 0.22, mat: "white" },
    {
      kind: "board",
      at: [2.53, 1.65, 19],
      width: 1.7,
      height: 0.85,
      bg: "#f1efe8",
      text: "General Notices",
      fg: "#2a2a2a",
    },
    { kind: "vending", at: [3, 21.2], color: "#20262c" },
    {
      name: "Fire extinguisher",
      kind: "box",
      at: [2.6, 0.9, 22.6],
      size: [0.15, 0.5, 0.15],
      mat: "red",
    },
    {
      name: "Window box",
      kind: "box",
      at: [3.3, 6.9, 24.3],
      size: [2.4, 1.7, 0.6],
      mat: "white",
    },
    {
      kind: "glazing",
      at: [3.3, 6.9, 24.62],
      width: 2.1,
      height: 1.4,
      cols: 4,
      rows: 2,
      face: "east",
    },
    {
      kind: "glazing",
      at: [-1.5, 1.8, 24.03],
      width: 0.9,
      height: 1.3,
      cols: 2,
      rows: 2,
      face: "east",
    },
    {
      name: "AC unit",
      kind: "box",
      at: [-2.6, 2.6, 24.2],
      size: [0.8, 0.5, 0.35],
      mat: "white",
    },
  ],
}
