'use client';
import { useRef, useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Box, Camera, Check, ChevronDown, Compass, Expand, Footprints, HelpCircle, Layers3, MapPin, Mouse, Navigation, RotateCcw, Video, X } from 'lucide-react';
import { CampusViewer, type ViewerHandle } from '@/components/campus-viewer';
import { PLACES, type PlaceId } from '@/lib/campus';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';

export default function App(){
 const viewer=useRef<ViewerHandle>(null);const [ready,setReady]=useState(false),[error,setError]=useState(''),[mode,setMode]=useState<'walk'|'overview'>('walk'),[active,setActive]=useState<PlaceId>('walkway'),[walking,setWalking]=useState(false),[source,setSource]=useState(false),[help,setHelp]=useState(false),[mobilePlaces,setMobilePlaces]=useState(false),[frame,setFrame]=useState(0),[pos,setPos]=useState({x:-4,z:18,y:4.2,yaw:0});
 const place=PLACES.find(p=>p.id===active)!;const level=pos.y>6?'Level 2':pos.y>2?'Level 1':'Ground';
 const goTo=(id:PlaceId)=>{setActive(id);viewer.current?.pause();viewer.current?.goTo(id);setMode('walk');setMobilePlaces(false);};
 const sourceFrames=[{file:'feature-wall.jpg',title:'Yellow feature wall',time:'00:07'},{file:'atrium.jpg',title:'Atrium & stair gallery',time:'00:16'},{file:'walkway.jpg',title:'Interior walkway',time:'00:25'},{file:'stairway.jpg',title:'Central stairway',time:'00:31'}];
 const openSource=()=>{viewer.current?.pause();setSource(true);};
 return <main className={'explorer '+(walking?'is-walking ':'')+(mode==='overview'?'is-overview':'')}>
  <header className="topbar"><a className="brand" href="./" aria-label="VIT Campus Explorer home"><span className="brand-mark">V</span><span><strong>VIT<span className="brand-separator">/</span><span className="brand-title">Campus Explorer</span></strong><small>Vidyalankar Institute of Technology · VOSS Labs</small></span></a><div className="top-actions"><span className="build-badge">INTERIOR MVP <span>01</span></span><button className="icon-button" title="Controls & about this map" aria-label="Controls and about this map" onClick={()=>{viewer.current?.pause();setHelp(true);}}><HelpCircle size={19}/></button><button className="icon-button fullscreen-button" title="Full screen" aria-label="Toggle full screen" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen?.().catch(()=>{});}}><Expand size={18}/></button></div></header>
  <div className="workspace">
   <aside className={'places-panel '+(mobilePlaces?'mobile-open':'')} aria-label="Explore viewpoints">
    <div className="panel-heading"><div className="eyebrow">EXPLORE THE INTERIOR</div><h1>A place you know.<br/>A new perspective.</h1><p>Step inside the central atrium.</p></div>
    <div className="section-label"><span>JUMP TO A PLACE</span><span>05</span></div>
    <nav className="place-list">{PLACES.map((p,i)=><button key={p.id} className={'place-card '+(active===p.id?'selected':'')} onClick={()=>goTo(p.id)}><span className="place-num">0{i+1}</span><span className="place-copy"><strong>{p.short}</strong><small>{p.level}</small></span>{active===p.id?<span className="selected-dot"/>:<MapPin size={15}/>}</button>)}</nav>
    <button className="source-card" onClick={openSource}><img src={`${import.meta.env.BASE_URL}reference/feature-wall.jpg`} alt="Yellow feature wall extracted from the college video"/><span className="source-image-shade"/><span className="source-camera"><Video size={17}/></span><span className="source-card-copy"><small>FROM YOUR WALKTHROUGH</small><strong>See the real space</strong><span>4 reference views <Camera size={13}/></span></span></button>
    <div className="coverage"><span className="coverage-symbol"><Box size={17}/></span><p><strong>Video-based reconstruction</strong><span>Visible atrium · Estimated dimensions</span></p></div>
    <footer className="panel-footer"><span>VOSS LABS · VIT, MUMBAI</span><span>EST. INTERIOR LAYOUT</span></footer>
   </aside>
   <section className="viewport" aria-label="3D campus map">
    <CampusViewer ref={viewer} onReady={()=>setReady(true)} onError={setError} onPosition={(x,z,y,yaw)=>setPos({x,z,y,yaw})} onLock={setWalking} onMode={setMode}/>
    <div className="scene-vignette"/>
    <div className="location-bar"><span className="location-icon"><MapPin size={16}/></span><span>Central atrium</span><span className="breadcrumb-slash">/</span><strong>{mode==='overview'?'Building overview':level}</strong><button className="mobile-places-toggle" aria-label="Show places" onClick={()=>setMobilePlaces(!mobilePlaces)}><ChevronDown size={18}/></button></div>
    <div className="compass" title="View orientation"><div style={{transform:`rotate(${-pos.yaw*180/Math.PI}deg)`}}><Navigation size={22} fill="currentColor"/></div><span>VIEW</span></div>
    {error?<div className="loading-state"><Box size={32}/><h2>3D view unavailable</h2><p>{error}</p><button onClick={()=>window.location.reload()}>Reload view</button></div>:!ready?<div className="loading-state"><span className="loading-orbit"/><h2>Opening the atrium</h2><p>Preparing your 3D campus…</p></div>:null}
    {ready&&!error&&!walking&&mode==='walk'&&<div className="walk-prompt"><div className="prompt-icon"><Footprints size={22}/></div><div><strong>You’re at {place.short.toLowerCase()}</strong><span>Drag to look around, or step into the space.</span></div><button onClick={()=>viewer.current?.start()}>Start walking <Footprints size={17}/></button></div>}
    {walking&&mode==='walk'&&<><div className="crosshair"/><div className="walking-notice"><Mouse size={14}/> Mouse to look <span/> <kbd>ESC</kbd> to release</div></>}
    {mode==='overview'&&<div className="overview-notice"><Box size={17}/><span>Drag to orbit · Scroll to zoom</span></div>}
    <div className="mini-map"><div className="map-head"><span><Layers3 size={14}/> {mode==='overview'?'ATRIUM':level.toUpperCase()}</span><span className="map-you"><i/> You</span></div><svg viewBox="0 0 190 190" role="img" aria-label="Estimated atrium floor plan and current position"><defs><pattern id="tilePattern" width="12" height="12" patternUnits="userSpaceOnUse"><path d="M12 0H0V12" fill="none" stroke="#e0dfd7" strokeWidth=".6"/></pattern></defs><rect x="40" y="13" width="110" height="162" rx="1" fill="#e9e8e0" stroke="#a5aaa3" strokeWidth="2"/><rect x="54" y="28" width="82" height="130" fill="url(#tilePattern)" stroke="#bac0b8"/><path d="M140 66v49" stroke="#d8db37" strokeWidth="9"/><path d="M43 28v40m0 11v25m0 11v27" stroke="#ad8666" strokeWidth="6"/><rect x="87" y="110" width="16" height="46" fill="#c9ceca"/>{[0,1,2,3,4,5,6,7].map(i=><path key={i} d={`M87 ${113+i*5}h16`} stroke="#919b93" strokeWidth="1"/>)}<rect x="55" y="42" width="13" height="44" fill="#b2bdba"/>{[0,1,2,3].map(i=><rect key={i} x={i%2?111:72} y={i<2?77:103} width="14" height="4" fill="#9d8d77"/>)}{PLACES.slice(0,4).map((p,i)=><g key={p.id} className="map-target" role="button" tabIndex={0} aria-label={`Go to ${p.short}`} onClick={()=>goTo(p.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')goTo(p.id);}}><circle cx={95+p.pos[0]*4.2} cy={94+p.pos[2]*3.7} r="8" fill={active===p.id?'#f7f7f0':'#fff'} stroke="#aaa99f"/><text x={95+p.pos[0]*4.2} y={97+p.pos[2]*3.7} textAnchor="middle" fill="#595e59" fontSize="8" fontFamily="Arial">{i+1}</text></g>)}{mode==='walk'&&<g transform={`translate(${95+pos.x*4.2} ${94+pos.z*3.7}) rotate(${-pos.yaw*180/Math.PI})`}><path d="M0 0-10-21Q0-27 10-21Z" fill="#b84d3725"/><circle r="5.5" fill="#b84d37" stroke="#fff" strokeWidth="2"/></g>}</svg><div className="map-foot">Approximate layout <span>INTERIOR ONLY</span></div></div>
    <div className="view-toolbar"><Tabs value={mode} onValueChange={v=>viewer.current?.setMode(v as 'walk'|'overview')}><TabsList className="mode-list"><TabsTrigger value="walk"><Footprints size={17}/>Walk</TabsTrigger><TabsTrigger value="overview"><Box size={17}/>3D overview</TabsTrigger></TabsList></Tabs><div className="toolbar-divider"/><button title="Return to starting view" aria-label="Return to starting view" onClick={()=>goTo('walkway')}><RotateCcw size={17}/></button><button title="View video frames" aria-label="View video reference frames" onClick={openSource}><Camera size={18}/></button></div>
    <div className="controls-guide"><span><kbd>W</kbd><span className="wasd"><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd></span></span><span>Move</span><i/><kbd>SHIFT</kbd><span>Run</span><i/><Mouse size={16}/><span>Look</span><i/><kbd>M</kbd><span>Map</span></div>
    <div className="touch-controls" aria-label="Touch movement controls">{[{k:'KeyW',c:'up',I:ArrowUp},{k:'KeyA',c:'left',I:ArrowLeft},{k:'KeyS',c:'down',I:ArrowDown},{k:'KeyD',c:'right',I:ArrowRight}].map(({k,c,I})=><button key={k} className={c} aria-label={`Move ${c}`} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);viewer.current?.move(k,true);}} onPointerUp={()=>viewer.current?.move(k,false)} onPointerCancel={()=>viewer.current?.move(k,false)}><I size={22}/></button>)}</div>
    <span className="render-label"><span/> LIVE 3D <b>·</b> THREE.JS</span>
   </section>
  </div>
  <Dialog open={source} onOpenChange={setSource}><DialogContent className="reference-dialog"><DialogHeader><div className="eyebrow">THE REAL SPACE</div><DialogTitle>Your video, frame by frame.</DialogTitle><DialogDescription>Extracted from IMG_4946.MOV · 44 seconds. Compare these views with the 3D reconstruction.</DialogDescription></DialogHeader><div className="reference-layout"><div className="frame-view"><img src={import.meta.env.BASE_URL+'reference/'+sourceFrames[frame].file} alt={sourceFrames[frame].title}/><span>{sourceFrames[frame].time}</span></div><div className="frame-options">{sourceFrames.map((f,i)=><button className={frame===i?'active':''} key={f.file} onClick={()=>setFrame(i)}><img src={import.meta.env.BASE_URL+'reference/'+f.file} alt=""/><span><strong>{f.title}</strong><small>{f.time} · Source frame</small></span>{frame===i&&<Check size={16}/>}</button>)}<div className="reference-note"><Box size={19}/><p>The geometry is interpreted from visible architecture. The clip does not provide a measured scan, a full floor plan, or unseen rooms.</p></div></div></div></DialogContent></Dialog>
  <Dialog open={help} onOpenChange={setHelp}><DialogContent className="help-dialog"><DialogHeader><div className="eyebrow">MAKE YOURSELF AT HOME</div><DialogTitle>A little help getting around.</DialogTitle><DialogDescription>Explore the atrium in first person, or inspect its layout from above.</DialogDescription></DialogHeader><div className="help-controls"><p><span><kbd>W A S D</kbd> or <kbd>↑ ↓ ← →</kbd></span><strong>Walk</strong></p><p><kbd>SHIFT</kbd><strong>Walk faster</strong></p><p><span>Mouse / touch drag</span><strong>Look around</strong></p><p><kbd>ESC</kbd><strong>Release mouse</strong></p><p><kbd>M</kbd><strong>Switch overview</strong></p></div><p className="help-note">Use the place list or numbered map points to jump to a viewpoint. On a phone, drag the scene to look and use the directional buttons to move.</p><div className="scope-note"><strong>What this map covers</strong><p>A conceptual reconstruction of the central atrium visible in your video. Dimensions, connections, and upper-level circulation are estimated. It is not a complete or surveyed college map.</p></div></DialogContent></Dialog>
 </main>;
}
